### ISSUE TITLE
enable README generation and add public dev docs

### ISSUE THREAD

**Issue by pgautier404** [momentohq/client-sdk-swift#56]
README generation and verification is commented out of the workflows right now pending addition of the cache client. The README generator can then use the example code snippets that are verified in CI for the cache client sample, in line with the other SDKs. Similarly, we need to wait to add this SDK to public dev docs until we have control and data plane released so it can also integrate CI-verified code samples.

- [x] release cache client
- [x] write CI-verified code snippets, including one for configuring cache and topics clients
- [x] update README generator
- [x] write Swift public dev docs

**Comment by anitarua** [comment]
Began draft PR for adding Swift to dev docs and to help identify which code snippets we should create: https://github.com/momentohq/public-dev-docs/pull/537
